dist: trusty
language: node_js
node_js: 8.1
sudo: true

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - bower install

script:
  - polymer lint --rules polymer-2 --input *.html
  - xvfb-run -s '-screen 0 1024x768x24' wct
